name: telemedice_project
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  curved_navigation_bar: ^1.0.3
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  shared_preferences: ^2.5.3
  image_picker: ^1.1.2
  firebase_storage: ^12.4.5
  random_string: ^2.3.1
  intl: ^0.20.2
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  google_maps_webservice: ^0.0.20-nullsafety
  table_calendar: ^3.0.9
  url_launcher: ^6.2.5
  jitsi_meet: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
